#!/usr/bin/env python3
import subprocess
import sys

import pymovements as pm

def main() -> int:
    subprocess.call(('pip', 'install', '-e', '.'))
    dataset_name = sys.argv[1]
    dataset = pm.Dataset(dataset_name, path=f'data/{dataset_name}')
    dataset.download(verbose=True)
    dataset.load()
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
